- name: installing {{COMPONENT}} components
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Enabling the Redis repo
  yum:
    name: redis
    state: present
    enablerepo: "remi"