- name: installing {{COMPONENT}} components
  shell: yum install epel-release yum-utils -y && yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y && yum-config-manager --enable remi && yum install redis -y | bash
  become: yes