- name: Installing Maven
  yum:
    name:
      - maven
    state: installed


- name: Adding user roboshop
  user:
    name: roboshop
    state: present

- name: Downloading and Extracting from git hub
  include_role:
    name: common
    tasks_from: git_checkout.yml
  vars:
    APP_DIR: /tmp/shipping
    EXTRACT_DIR: /tmp

- name: rename the files
  become: yes
  shell: mv /tmp/shipping-main/* /home/roboshop/shipping/ | bash


- name: maven clean package
  become_user: roboshop
  shell: maven clean package && mv target/shipping-1.0.jar shipping.jar | bash
  args:
    chdir: /home/roboshop/shipping



#- name: Downloading&Extraction from Github to roboshop
#  ansible.builtin.git:
#    repo: https://github.com/roboshop-devops-project/shipping/archive/main.zip
#    dest: /home/roboshop/
#    unarchive: /tmp/shipping.zip
#    remote_src: yes
#

