- name: setup roboshop project
  hosts: FRONTEND
  become: yes
  roles:
    - name: loading the frontend
      role: frontend
  tags:
    - frontend

- name: setup mongodb
  hosts: MONGODB
  become: yes
  roles:
    - name: loading the mongodb
      role: mongodb
  tags:
    - mongodb



- name: setting up the catalogue
  hosts: CATALOGUE
  roles:
    - name: working on catalogue
      role: catalogue
  tags:
    -catalogue