- name: Clean Known Hosts entries
  hosts: localhost
  tasks:
    - name: Clear Known Hosts file
      file:
        path: ~/.ssh/known_hosts
        state: absent

- name: LOADING THE FRONTEND
  hosts: FRONTEND
  become: yes
  tags:
    - front
  roles:
  - name: loading the frontend
    role: frontend

- name:  LOADING THE MONGOdb
  hosts: MONGODB
  tags:
    - mongodb
  become: yes
  roles:
    - name: loading DataBase
      role: mongodb

- name:  LOADING THE CATALOGUE
  hosts: CATALOGUE
  tags:
    - catalogue
  become: yes
  roles:
    - name: loading CAtalogue service
      role: catalogue




