- name: setup roboshop project
  hosts: hosts
  become: yes
  roles:
    - name: loading the frontend
      role: frontend
  tags:
    - frontend

- name: setup mongodb
  hosts: hosts
  become: yes
  roles:
    - name: loading the mongodb
      role: mongodb
  tags:
    - mongodb


- name: setting up the catalogue
  hosts: hosts
  roles:
    - name: working on catalogue
      role: catalogue
  tags:
    -catalogue