- name: LOADING THE FRONTEND
  hosts: FRONTEND
  tags:
    - front
  become: yes
  roles:
    - name: loading the frontend
      role: frontend

- name:  LOADING THE MONGOdb
  hosts: MONGODB
  tags:
    - mongodb
  become: yes
  roles:
    - name: loading DataBase
      role: mongodb





