- name: Clean Known Hosts entries
  hosts: localhost
  tasks:
    - name: Clear Known Hosts file
      file:
        path: ~/.ssh/known_hosts
        state: absent

- name: LOADING THE FRONTEND
  hosts: FRONTEND
  become: yes
  tags:
    - frontend
  roles:
  - name: loading the frontend
    role: frontend

- name: LOADING THE MONGODB
  hosts: MONGODB
  become: yes
  tags:
    - mongodb
  roles:
    - name: loading the mongodb
      role: mongodb

- name: LOADING THE CATALOGUE
  hosts: CATALOGUE
  become: yes
  tags:
    - catalogue
  roles:
    - name: loading the catalogue
      role: catalogue

- name: LOADING THE REDIS
  hosts: REDIS
  become: yes
  tags:
    - redis
  roles:
    - name: loading the redis
      role: redis

- name: LOADING THE USER
  hosts: USER
  become: yes
  tags:
    - user
  roles:
    - name: loading the user
      role: user

- name: LOADING THE CART
  hosts: CART
  become: yes
  tags:
    - cart
  roles:
    - name: loading the cart
      role: cart

- name: LOADING THE MYSQL
  hosts: MYSQL
  become: yes
  tags:
    - mysql
  roles:
    - name: loading the mysql
      role: mysql
