- name: demo on variable
  hosts: all
  vars:
    url: paly.example.com
  tasks:
    - name: print variable
      debug:
        msg: URL={{url}}
    - name: print from task level
      vars:
        url: task.example.com
      debug:
        msg: url == {{url}}

- name: print from user input
  hosts: all
  vars_prompt:
    - name: url
      prompt: enter the numbwer
      private: no
  tasks:
    - name: prinitng the user input
      debug:
        msg: url == {{url}}

- name: print address fron ansible-pull.yml
  hosts: all
  tasks:
    - name: printing from ansible-pull.yml file
      debug:
        msg: url=={{url}}

- name: printing from facts
  hosts: all
  tasks:
    - name: printingggg
      debug:
        msg: python version ={{ansible_python_version}}







## for i in cart catalogue frontend mongodb mysql payment rabbitmq redis shipping user ; do echo -e "[$(echo $i | tr [a-z] [A-Z])]\n$i.roboshop.internal" ; done




