- name: Installing the payment component
  yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Adding user Roboshop
  user:
    name: roboshop
    comment: roboshop project user

- name: downloading from github
  include_role:
    name: common
    tasks_from: git_checkout.yml
  vars:
    APP_DIR: /home/roboshop/{{COMPONENT}}
    EXTRACT_DIR: /tmp

- name: Moving the files inside the roboshop
  shell: mv /tmp/payment-main /home/roboshop/payment | bash
  become_user: roboshop

- name: Installing the Dependencies
  become: yes
  pip:
    requirements: /home/roboshop/payment/requirements.txt
    executable: pip3

- name: Updating the payment.ini file
  become: yes
  shell: sed -e 's/uid = 1/uid = 1001/g' sed -e 's/gid = 1/gid = 1001/g' /home/roboshop/payment/payment.ini | bash


- name: Starting the service
  systemd:
    name: payment
    state: restarted
    daemon_reload: yes
    enabled: yes