- name: Installing the payment component
  yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Adding user Roboshop
  user:
    name: roboshop
    comment: roboshop project user

- name: downloading from github
  include_role:
    name: common
    tasks_from: git_checkout.yml
  vars:
    APP_DIR: /home/roboshop/{{COMPONENT}}
    EXTRACT_DIR: /tmp

- name: Moving the files inside the roboshop
  shell: mv /tmp/payment-main /home/roboshop/payment | bash
  become: yes

- name: Installing the Dependencies
  become: yes
  pip:
    requirements: /home/roboshop/payment/requirements.txt
    executable: pip3

- name: Updating the payment.ini file
  become: yes
  lineinfile:
    dest: /home/roboshop/payment/payment.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    items:
      - { regexp: 'uid = 1', line: 'uid = 1001' }
      - { regexp: 'gid = 1', line: 'gid = 1001' }

- name: Updating the systemd file
  copy:
    src: payment.service
    dest: /etc/systemd/system/payment.service


- name: Starting the service
  systemd:
    name: payment
    state: restarted
    daemon_reload: yes
    enabled: yes