- name: Installing the payment component
  yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Adding user Roboshop
  user:
    name: roboshop
    comment: roboshop project user

- name: downloading from github
  include_role:
    name: common
    tasks_from: git_checkout.yml
  vars:
    APP_DIR: /home/roboshop/{{COMPONENT}}
    EXTRACT_DIR: /tmp

- name: Moving the files inside the roboshop
  shell: mv /tmp/payment-main /home/roboshop/payment | bash
  become: yes


