- name: working in frontend
  debug:
    msg: component=catalogue

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: ansible create directory example
  file:
    path: /usr/share/nginx/html
    state: directory

- name: unarchive repo
  unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /usr/share/nginx/html
    remote_src: true


- name: Deleting previous content
  file:
    state: absent
    path: /usr/share/nginx/html/



- name: moving files to nginx
  file:
    src: /usr/share/nginx/html/frontend-main/
    path: /usr/share/nginx/html/
    state: hard

- name: moving files to nginx
  file:
    src: /usr/share/nginx/html/static/
    path: /usr/share/nginx/html/
    state: hard

