
- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Start Nginx Service
  service:
    name: nginx
    state: started

- name: Remove old contents
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Unarchive file from github
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /usr/share/nginx
    remote_src: yes

- name: copy all content frontend
  ansible.builtin.copy:
    src: /usr/share/nginx/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Copy config file
  copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start Nginx Service
  service:
    name: nginx
    state: restarted
    enabled: yes


