
- name: Install nginx
  yum:
    name: nginx
    state: installed


- name: service NGINX start
  ansible.builtin.systemd:
    name: nginx
    state: started


- name: Remove old contents
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Unarchive file from github
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /usr/share/nginx
    remote_src: yes

- name: copy all content frontend
  ansible.builtin.copy:
    src: /usr/share/nginx/frontend-main/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: copy all content static
  ansible.builtin.copy:
    src: /usr/share/nginx/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name : copying roboshop config file
  copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/

- name: Start Nginx Service
  ansible.builtin.systemd:
    state: reloaded
    name: nginx
    enabled: yes



