- name: working in frontend
  debug:
    msg: component=catalogue

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Creates directory
  file:
    path: /usr/share/nginx/html
    state: directory

- name: unarchive repo
  unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /usr/share/nginx/html
    remote_src: true

- name: copy html file
  copy:
    src: /usr/share/nginx/html/frontend-main/
    dest: /usr/share/nginx/html/
    remote_src: yes
