- name: Setting up the catalogue component
  yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: installed

- name: Add the user Roboshop
  ansible.builtin.user:
    name: roboshop
    comment: adding

- name: Git checkout
  ansible.builtin.git:
    repo: "https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip"
    dest: /tmp/catalogue.zip

- name: Unarchive the package
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /home/roboshop/
    remote_src: yes

- name: Install node.js package.
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: copy systemd files
  copy:
    src: /home/roboshop/{{COMPONENT}}/systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: SYSTEM CTL restart service
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes